name: 'K7z Upgrade'
description: 'Upgrade helm installs under K7z'
author: 'manicomio.dev'

inputs:
  base_url:
    description:
      'the base url of the k7z instance, with https and no trailing slash'
    required: true
  team_name:
    description: 'the name of the team'
    required: true
  project_name:
    description: 'the name of the project'
    required: true
  api_key:
    description: 'the api secret'
    required: true
  ref:
    description: 'branch name or commit id'
    required: true
  data:
    description: 'extra data to pass'
    required: false

outputs:
  status:
    description: 'the http status code of the upgrade'

runs:
  using: node20
  main: dist/index.js
